"""Add users

Revision ID: 36936f0c6882
Revises: 6774d3a6d9a3
Create Date: 2024-12-12 12:16:19.641799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36936f0c6882'
down_revision = '6774d3a6d9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
