"""newMigration

Revision ID: 97a6e8d315df
Revises: 5fa3b683a920
Create Date: 2024-12-27 13:53:40.701618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a6e8d315df'
down_revision = '5fa3b683a920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prev_precip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('prev_precip_accum', sa.String(length=128), nullable=False),
    sa.Column('last_precip_accum_long', sa.String(length=128), nullable=False),
    sa.Column('precip_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stations_div_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precip_accum_long', sa.String(length=20), nullable=False))

    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precip_accum_long', sa.String(length=128), nullable=False))
        batch_op.alter_column('precip_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.alter_column('precip_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('precip_accum_long')

    with op.batch_alter_table('stations_div_positions', schema=None) as batch_op:
        batch_op.drop_column('precip_accum_long')

    op.drop_table('prev_precip')
    # ### end Alembic commands ###
