"""first database

Revision ID: e612bd2e6f55
Revises: 
Create Date: 2024-12-11 11:52:47.549463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e612bd2e6f55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.alter_column('station_name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('api',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=False)

    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.alter_column('station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('precip_rate',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('precip_accum',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('precip_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.alter_column('precip_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('precip_accum',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('precip_rate',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('api',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('station_name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###
